/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRouteRouteImport } from './routes/api/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardGuildIdRouteRouteImport } from './routes/dashboard/$guildId/route'
import { Route as ApiGuildsIndexRouteImport } from './routes/api/guilds/index'
import { Route as DashboardGuildIdIndexRouteImport } from './routes/dashboard/$guildId/index'
import { Route as DashboardGuildIdActivityRouteImport } from './routes/dashboard/$guildId/activity'
import { Route as DashboardGuildIdAiRouteImport } from './routes/dashboard/$guildId/ai'
import { Route as DashboardGuildIdCommandsRouteImport } from './routes/dashboard/$guildId/commands'
import { Route as DashboardGuildIdRemindersRouteImport } from './routes/dashboard/$guildId/reminders'
import { Route as DashboardGuildIdRespondersRouteImport } from './routes/dashboard/$guildId/responders'
import { Route as DashboardGuildIdSchedulesRouteImport } from './routes/dashboard/$guildId/schedules'
import { Route as DashboardGuildIdSendRouteImport } from './routes/dashboard/$guildId/send'
import { Route as DashboardGuildIdWelcomeRouteImport } from './routes/dashboard/$guildId/welcome'
import { Route as ApiGuildsGuildIdIndexRouteImport } from './routes/api/guilds/$guildId/index'
import { Route as ApiGuildsGuildIdActivityRouteImport } from './routes/api/guilds/$guildId/activity'
import { Route as ApiGuildsGuildIdChannelsRouteImport } from './routes/api/guilds/$guildId/channels'
import { Route as ApiGuildsGuildIdMembersRouteImport } from './routes/api/guilds/$guildId/members'
import { Route as ApiGuildsGuildIdMessagesRouteImport } from './routes/api/guilds/$guildId/messages'
import { Route as ApiGuildsGuildIdRolesRouteImport } from './routes/api/guilds/$guildId/roles'
import { Route as ApiGuildsGuildIdWelcomeRouteImport } from './routes/api/guilds/$guildId/welcome'
import { Route as ApiGuildsGuildIdAiIndexRouteImport } from './routes/api/guilds/$guildId/ai/index'
import { Route as ApiGuildsGuildIdAiTestRouteImport } from './routes/api/guilds/$guildId/ai/test'
import { Route as ApiGuildsGuildIdCommandsIndexRouteImport } from './routes/api/guilds/$guildId/commands/index'
import { Route as ApiGuildsGuildIdCommandsIdRouteImport } from './routes/api/guilds/$guildId/commands/$id'
import { Route as ApiGuildsGuildIdRemindersIndexRouteImport } from './routes/api/guilds/$guildId/reminders/index'
import { Route as ApiGuildsGuildIdRemindersIdRouteImport } from './routes/api/guilds/$guildId/reminders/$id'
import { Route as ApiGuildsGuildIdRemindersSettingsRouteImport } from './routes/api/guilds/$guildId/reminders/settings'
import { Route as ApiGuildsGuildIdRespondersIndexRouteImport } from './routes/api/guilds/$guildId/responders/index'
import { Route as ApiGuildsGuildIdRespondersIdRouteImport } from './routes/api/guilds/$guildId/responders/$id'
import { Route as ApiGuildsGuildIdSchedulesIndexRouteImport } from './routes/api/guilds/$guildId/schedules/index'
import { Route as ApiGuildsGuildIdSchedulesIdIndexRouteImport } from './routes/api/guilds/$guildId/schedules/$id/index'
import { Route as ApiGuildsGuildIdSchedulesIdSendRouteImport } from './routes/api/guilds/$guildId/schedules/$id/send'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRouteRoute = ApiRouteRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => ApiRouteRoute,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGuildIdRouteRoute = DashboardGuildIdRouteRouteImport.update({
  id: '/$guildId',
  path: '/$guildId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiGuildsIndexRoute = ApiGuildsIndexRouteImport.update({
  id: '/guilds/',
  path: '/guilds/',
  getParentRoute: () => ApiRouteRoute,
} as any)
const DashboardGuildIdIndexRoute = DashboardGuildIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardGuildIdRouteRoute,
} as any)
const DashboardGuildIdActivityRoute =
  DashboardGuildIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => DashboardGuildIdRouteRoute,
  } as any)
const DashboardGuildIdAiRoute = DashboardGuildIdAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => DashboardGuildIdRouteRoute,
} as any)
const DashboardGuildIdCommandsRoute =
  DashboardGuildIdCommandsRouteImport.update({
    id: '/commands',
    path: '/commands',
    getParentRoute: () => DashboardGuildIdRouteRoute,
  } as any)
const DashboardGuildIdRemindersRoute =
  DashboardGuildIdRemindersRouteImport.update({
    id: '/reminders',
    path: '/reminders',
    getParentRoute: () => DashboardGuildIdRouteRoute,
  } as any)
const DashboardGuildIdRespondersRoute =
  DashboardGuildIdRespondersRouteImport.update({
    id: '/responders',
    path: '/responders',
    getParentRoute: () => DashboardGuildIdRouteRoute,
  } as any)
const DashboardGuildIdSchedulesRoute =
  DashboardGuildIdSchedulesRouteImport.update({
    id: '/schedules',
    path: '/schedules',
    getParentRoute: () => DashboardGuildIdRouteRoute,
  } as any)
const DashboardGuildIdSendRoute = DashboardGuildIdSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => DashboardGuildIdRouteRoute,
} as any)
const DashboardGuildIdWelcomeRoute = DashboardGuildIdWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => DashboardGuildIdRouteRoute,
} as any)
const ApiGuildsGuildIdIndexRoute = ApiGuildsGuildIdIndexRouteImport.update({
  id: '/guilds/$guildId/',
  path: '/guilds/$guildId/',
  getParentRoute: () => ApiRouteRoute,
} as any)
const ApiGuildsGuildIdActivityRoute =
  ApiGuildsGuildIdActivityRouteImport.update({
    id: '/guilds/$guildId/activity',
    path: '/guilds/$guildId/activity',
    getParentRoute: () => ApiRouteRoute,
  } as any)
const ApiGuildsGuildIdChannelsRoute =
  ApiGuildsGuildIdChannelsRouteImport.update({
    id: '/guilds/$guildId/channels',
    path: '/guilds/$guildId/channels',
    getParentRoute: () => ApiRouteRoute,
  } as any)
const ApiGuildsGuildIdMembersRoute = ApiGuildsGuildIdMembersRouteImport.update({
  id: '/guilds/$guildId/members',
  path: '/guilds/$guildId/members',
  getParentRoute: () => ApiRouteRoute,
} as any)
const ApiGuildsGuildIdMessagesRoute =
  ApiGuildsGuildIdMessagesRouteImport.update({
    id: '/guilds/$guildId/messages',
    path: '/guilds/$guildId/messages',
    getParentRoute: () => ApiRouteRoute,
  } as any)
const ApiGuildsGuildIdRolesRoute = ApiGuildsGuildIdRolesRouteImport.update({
  id: '/guilds/$guildId/roles',
  path: '/guilds/$guildId/roles',
  getParentRoute: () => ApiRouteRoute,
} as any)
const ApiGuildsGuildIdWelcomeRoute = ApiGuildsGuildIdWelcomeRouteImport.update({
  id: '/guilds/$guildId/welcome',
  path: '/guilds/$guildId/welcome',
  getParentRoute: () => ApiRouteRoute,
} as any)
const ApiGuildsGuildIdAiIndexRoute = ApiGuildsGuildIdAiIndexRouteImport.update({
  id: '/guilds/$guildId/ai/',
  path: '/guilds/$guildId/ai/',
  getParentRoute: () => ApiRouteRoute,
} as any)
const ApiGuildsGuildIdAiTestRoute = ApiGuildsGuildIdAiTestRouteImport.update({
  id: '/guilds/$guildId/ai/test',
  path: '/guilds/$guildId/ai/test',
  getParentRoute: () => ApiRouteRoute,
} as any)
const ApiGuildsGuildIdCommandsIndexRoute =
  ApiGuildsGuildIdCommandsIndexRouteImport.update({
    id: '/guilds/$guildId/commands/',
    path: '/guilds/$guildId/commands/',
    getParentRoute: () => ApiRouteRoute,
  } as any)
const ApiGuildsGuildIdCommandsIdRoute =
  ApiGuildsGuildIdCommandsIdRouteImport.update({
    id: '/guilds/$guildId/commands/$id',
    path: '/guilds/$guildId/commands/$id',
    getParentRoute: () => ApiRouteRoute,
  } as any)
const ApiGuildsGuildIdRemindersIndexRoute =
  ApiGuildsGuildIdRemindersIndexRouteImport.update({
    id: '/guilds/$guildId/reminders/',
    path: '/guilds/$guildId/reminders/',
    getParentRoute: () => ApiRouteRoute,
  } as any)
const ApiGuildsGuildIdRemindersIdRoute =
  ApiGuildsGuildIdRemindersIdRouteImport.update({
    id: '/guilds/$guildId/reminders/$id',
    path: '/guilds/$guildId/reminders/$id',
    getParentRoute: () => ApiRouteRoute,
  } as any)
const ApiGuildsGuildIdRemindersSettingsRoute =
  ApiGuildsGuildIdRemindersSettingsRouteImport.update({
    id: '/guilds/$guildId/reminders/settings',
    path: '/guilds/$guildId/reminders/settings',
    getParentRoute: () => ApiRouteRoute,
  } as any)
const ApiGuildsGuildIdRespondersIndexRoute =
  ApiGuildsGuildIdRespondersIndexRouteImport.update({
    id: '/guilds/$guildId/responders/',
    path: '/guilds/$guildId/responders/',
    getParentRoute: () => ApiRouteRoute,
  } as any)
const ApiGuildsGuildIdRespondersIdRoute =
  ApiGuildsGuildIdRespondersIdRouteImport.update({
    id: '/guilds/$guildId/responders/$id',
    path: '/guilds/$guildId/responders/$id',
    getParentRoute: () => ApiRouteRoute,
  } as any)
const ApiGuildsGuildIdSchedulesIndexRoute =
  ApiGuildsGuildIdSchedulesIndexRouteImport.update({
    id: '/guilds/$guildId/schedules/',
    path: '/guilds/$guildId/schedules/',
    getParentRoute: () => ApiRouteRoute,
  } as any)
const ApiGuildsGuildIdSchedulesIdIndexRoute =
  ApiGuildsGuildIdSchedulesIdIndexRouteImport.update({
    id: '/guilds/$guildId/schedules/$id/',
    path: '/guilds/$guildId/schedules/$id/',
    getParentRoute: () => ApiRouteRoute,
  } as any)
const ApiGuildsGuildIdSchedulesIdSendRoute =
  ApiGuildsGuildIdSchedulesIdSendRouteImport.update({
    id: '/guilds/$guildId/schedules/$id/send',
    path: '/guilds/$guildId/schedules/$id/send',
    getParentRoute: () => ApiRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api': typeof ApiRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/$guildId': typeof DashboardGuildIdRouteRouteWithChildren
  '/api/stats': typeof ApiStatsRoute
  '/api/status': typeof ApiStatusRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$guildId/activity': typeof DashboardGuildIdActivityRoute
  '/dashboard/$guildId/ai': typeof DashboardGuildIdAiRoute
  '/dashboard/$guildId/commands': typeof DashboardGuildIdCommandsRoute
  '/dashboard/$guildId/reminders': typeof DashboardGuildIdRemindersRoute
  '/dashboard/$guildId/responders': typeof DashboardGuildIdRespondersRoute
  '/dashboard/$guildId/schedules': typeof DashboardGuildIdSchedulesRoute
  '/dashboard/$guildId/send': typeof DashboardGuildIdSendRoute
  '/dashboard/$guildId/welcome': typeof DashboardGuildIdWelcomeRoute
  '/api/guilds/': typeof ApiGuildsIndexRoute
  '/dashboard/$guildId/': typeof DashboardGuildIdIndexRoute
  '/api/guilds/$guildId/activity': typeof ApiGuildsGuildIdActivityRoute
  '/api/guilds/$guildId/channels': typeof ApiGuildsGuildIdChannelsRoute
  '/api/guilds/$guildId/members': typeof ApiGuildsGuildIdMembersRoute
  '/api/guilds/$guildId/messages': typeof ApiGuildsGuildIdMessagesRoute
  '/api/guilds/$guildId/roles': typeof ApiGuildsGuildIdRolesRoute
  '/api/guilds/$guildId/welcome': typeof ApiGuildsGuildIdWelcomeRoute
  '/api/guilds/$guildId/': typeof ApiGuildsGuildIdIndexRoute
  '/api/guilds/$guildId/ai/test': typeof ApiGuildsGuildIdAiTestRoute
  '/api/guilds/$guildId/commands/$id': typeof ApiGuildsGuildIdCommandsIdRoute
  '/api/guilds/$guildId/reminders/$id': typeof ApiGuildsGuildIdRemindersIdRoute
  '/api/guilds/$guildId/reminders/settings': typeof ApiGuildsGuildIdRemindersSettingsRoute
  '/api/guilds/$guildId/responders/$id': typeof ApiGuildsGuildIdRespondersIdRoute
  '/api/guilds/$guildId/ai/': typeof ApiGuildsGuildIdAiIndexRoute
  '/api/guilds/$guildId/commands/': typeof ApiGuildsGuildIdCommandsIndexRoute
  '/api/guilds/$guildId/reminders/': typeof ApiGuildsGuildIdRemindersIndexRoute
  '/api/guilds/$guildId/responders/': typeof ApiGuildsGuildIdRespondersIndexRoute
  '/api/guilds/$guildId/schedules/': typeof ApiGuildsGuildIdSchedulesIndexRoute
  '/api/guilds/$guildId/schedules/$id/send': typeof ApiGuildsGuildIdSchedulesIdSendRoute
  '/api/guilds/$guildId/schedules/$id/': typeof ApiGuildsGuildIdSchedulesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRouteRouteWithChildren
  '/api/stats': typeof ApiStatsRoute
  '/api/status': typeof ApiStatusRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/$guildId/activity': typeof DashboardGuildIdActivityRoute
  '/dashboard/$guildId/ai': typeof DashboardGuildIdAiRoute
  '/dashboard/$guildId/commands': typeof DashboardGuildIdCommandsRoute
  '/dashboard/$guildId/reminders': typeof DashboardGuildIdRemindersRoute
  '/dashboard/$guildId/responders': typeof DashboardGuildIdRespondersRoute
  '/dashboard/$guildId/schedules': typeof DashboardGuildIdSchedulesRoute
  '/dashboard/$guildId/send': typeof DashboardGuildIdSendRoute
  '/dashboard/$guildId/welcome': typeof DashboardGuildIdWelcomeRoute
  '/api/guilds': typeof ApiGuildsIndexRoute
  '/dashboard/$guildId': typeof DashboardGuildIdIndexRoute
  '/api/guilds/$guildId/activity': typeof ApiGuildsGuildIdActivityRoute
  '/api/guilds/$guildId/channels': typeof ApiGuildsGuildIdChannelsRoute
  '/api/guilds/$guildId/members': typeof ApiGuildsGuildIdMembersRoute
  '/api/guilds/$guildId/messages': typeof ApiGuildsGuildIdMessagesRoute
  '/api/guilds/$guildId/roles': typeof ApiGuildsGuildIdRolesRoute
  '/api/guilds/$guildId/welcome': typeof ApiGuildsGuildIdWelcomeRoute
  '/api/guilds/$guildId': typeof ApiGuildsGuildIdIndexRoute
  '/api/guilds/$guildId/ai/test': typeof ApiGuildsGuildIdAiTestRoute
  '/api/guilds/$guildId/commands/$id': typeof ApiGuildsGuildIdCommandsIdRoute
  '/api/guilds/$guildId/reminders/$id': typeof ApiGuildsGuildIdRemindersIdRoute
  '/api/guilds/$guildId/reminders/settings': typeof ApiGuildsGuildIdRemindersSettingsRoute
  '/api/guilds/$guildId/responders/$id': typeof ApiGuildsGuildIdRespondersIdRoute
  '/api/guilds/$guildId/ai': typeof ApiGuildsGuildIdAiIndexRoute
  '/api/guilds/$guildId/commands': typeof ApiGuildsGuildIdCommandsIndexRoute
  '/api/guilds/$guildId/reminders': typeof ApiGuildsGuildIdRemindersIndexRoute
  '/api/guilds/$guildId/responders': typeof ApiGuildsGuildIdRespondersIndexRoute
  '/api/guilds/$guildId/schedules': typeof ApiGuildsGuildIdSchedulesIndexRoute
  '/api/guilds/$guildId/schedules/$id/send': typeof ApiGuildsGuildIdSchedulesIdSendRoute
  '/api/guilds/$guildId/schedules/$id': typeof ApiGuildsGuildIdSchedulesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api': typeof ApiRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/$guildId': typeof DashboardGuildIdRouteRouteWithChildren
  '/api/stats': typeof ApiStatsRoute
  '/api/status': typeof ApiStatusRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$guildId/activity': typeof DashboardGuildIdActivityRoute
  '/dashboard/$guildId/ai': typeof DashboardGuildIdAiRoute
  '/dashboard/$guildId/commands': typeof DashboardGuildIdCommandsRoute
  '/dashboard/$guildId/reminders': typeof DashboardGuildIdRemindersRoute
  '/dashboard/$guildId/responders': typeof DashboardGuildIdRespondersRoute
  '/dashboard/$guildId/schedules': typeof DashboardGuildIdSchedulesRoute
  '/dashboard/$guildId/send': typeof DashboardGuildIdSendRoute
  '/dashboard/$guildId/welcome': typeof DashboardGuildIdWelcomeRoute
  '/api/guilds/': typeof ApiGuildsIndexRoute
  '/dashboard/$guildId/': typeof DashboardGuildIdIndexRoute
  '/api/guilds/$guildId/activity': typeof ApiGuildsGuildIdActivityRoute
  '/api/guilds/$guildId/channels': typeof ApiGuildsGuildIdChannelsRoute
  '/api/guilds/$guildId/members': typeof ApiGuildsGuildIdMembersRoute
  '/api/guilds/$guildId/messages': typeof ApiGuildsGuildIdMessagesRoute
  '/api/guilds/$guildId/roles': typeof ApiGuildsGuildIdRolesRoute
  '/api/guilds/$guildId/welcome': typeof ApiGuildsGuildIdWelcomeRoute
  '/api/guilds/$guildId/': typeof ApiGuildsGuildIdIndexRoute
  '/api/guilds/$guildId/ai/test': typeof ApiGuildsGuildIdAiTestRoute
  '/api/guilds/$guildId/commands/$id': typeof ApiGuildsGuildIdCommandsIdRoute
  '/api/guilds/$guildId/reminders/$id': typeof ApiGuildsGuildIdRemindersIdRoute
  '/api/guilds/$guildId/reminders/settings': typeof ApiGuildsGuildIdRemindersSettingsRoute
  '/api/guilds/$guildId/responders/$id': typeof ApiGuildsGuildIdRespondersIdRoute
  '/api/guilds/$guildId/ai/': typeof ApiGuildsGuildIdAiIndexRoute
  '/api/guilds/$guildId/commands/': typeof ApiGuildsGuildIdCommandsIndexRoute
  '/api/guilds/$guildId/reminders/': typeof ApiGuildsGuildIdRemindersIndexRoute
  '/api/guilds/$guildId/responders/': typeof ApiGuildsGuildIdRespondersIndexRoute
  '/api/guilds/$guildId/schedules/': typeof ApiGuildsGuildIdSchedulesIndexRoute
  '/api/guilds/$guildId/schedules/$id/send': typeof ApiGuildsGuildIdSchedulesIdSendRoute
  '/api/guilds/$guildId/schedules/$id/': typeof ApiGuildsGuildIdSchedulesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api'
    | '/dashboard'
    | '/dashboard/$guildId'
    | '/api/stats'
    | '/api/status'
    | '/dashboard/'
    | '/dashboard/$guildId/activity'
    | '/dashboard/$guildId/ai'
    | '/dashboard/$guildId/commands'
    | '/dashboard/$guildId/reminders'
    | '/dashboard/$guildId/responders'
    | '/dashboard/$guildId/schedules'
    | '/dashboard/$guildId/send'
    | '/dashboard/$guildId/welcome'
    | '/api/guilds/'
    | '/dashboard/$guildId/'
    | '/api/guilds/$guildId/activity'
    | '/api/guilds/$guildId/channels'
    | '/api/guilds/$guildId/members'
    | '/api/guilds/$guildId/messages'
    | '/api/guilds/$guildId/roles'
    | '/api/guilds/$guildId/welcome'
    | '/api/guilds/$guildId/'
    | '/api/guilds/$guildId/ai/test'
    | '/api/guilds/$guildId/commands/$id'
    | '/api/guilds/$guildId/reminders/$id'
    | '/api/guilds/$guildId/reminders/settings'
    | '/api/guilds/$guildId/responders/$id'
    | '/api/guilds/$guildId/ai/'
    | '/api/guilds/$guildId/commands/'
    | '/api/guilds/$guildId/reminders/'
    | '/api/guilds/$guildId/responders/'
    | '/api/guilds/$guildId/schedules/'
    | '/api/guilds/$guildId/schedules/$id/send'
    | '/api/guilds/$guildId/schedules/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api'
    | '/api/stats'
    | '/api/status'
    | '/dashboard'
    | '/dashboard/$guildId/activity'
    | '/dashboard/$guildId/ai'
    | '/dashboard/$guildId/commands'
    | '/dashboard/$guildId/reminders'
    | '/dashboard/$guildId/responders'
    | '/dashboard/$guildId/schedules'
    | '/dashboard/$guildId/send'
    | '/dashboard/$guildId/welcome'
    | '/api/guilds'
    | '/dashboard/$guildId'
    | '/api/guilds/$guildId/activity'
    | '/api/guilds/$guildId/channels'
    | '/api/guilds/$guildId/members'
    | '/api/guilds/$guildId/messages'
    | '/api/guilds/$guildId/roles'
    | '/api/guilds/$guildId/welcome'
    | '/api/guilds/$guildId'
    | '/api/guilds/$guildId/ai/test'
    | '/api/guilds/$guildId/commands/$id'
    | '/api/guilds/$guildId/reminders/$id'
    | '/api/guilds/$guildId/reminders/settings'
    | '/api/guilds/$guildId/responders/$id'
    | '/api/guilds/$guildId/ai'
    | '/api/guilds/$guildId/commands'
    | '/api/guilds/$guildId/reminders'
    | '/api/guilds/$guildId/responders'
    | '/api/guilds/$guildId/schedules'
    | '/api/guilds/$guildId/schedules/$id/send'
    | '/api/guilds/$guildId/schedules/$id'
  id:
    | '__root__'
    | '/'
    | '/api'
    | '/dashboard'
    | '/dashboard/$guildId'
    | '/api/stats'
    | '/api/status'
    | '/dashboard/'
    | '/dashboard/$guildId/activity'
    | '/dashboard/$guildId/ai'
    | '/dashboard/$guildId/commands'
    | '/dashboard/$guildId/reminders'
    | '/dashboard/$guildId/responders'
    | '/dashboard/$guildId/schedules'
    | '/dashboard/$guildId/send'
    | '/dashboard/$guildId/welcome'
    | '/api/guilds/'
    | '/dashboard/$guildId/'
    | '/api/guilds/$guildId/activity'
    | '/api/guilds/$guildId/channels'
    | '/api/guilds/$guildId/members'
    | '/api/guilds/$guildId/messages'
    | '/api/guilds/$guildId/roles'
    | '/api/guilds/$guildId/welcome'
    | '/api/guilds/$guildId/'
    | '/api/guilds/$guildId/ai/test'
    | '/api/guilds/$guildId/commands/$id'
    | '/api/guilds/$guildId/reminders/$id'
    | '/api/guilds/$guildId/reminders/settings'
    | '/api/guilds/$guildId/responders/$id'
    | '/api/guilds/$guildId/ai/'
    | '/api/guilds/$guildId/commands/'
    | '/api/guilds/$guildId/reminders/'
    | '/api/guilds/$guildId/responders/'
    | '/api/guilds/$guildId/schedules/'
    | '/api/guilds/$guildId/schedules/$id/send'
    | '/api/guilds/$guildId/schedules/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRouteRoute: typeof ApiRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/status': {
      id: '/api/status'
      path: '/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/$guildId': {
      id: '/dashboard/$guildId'
      path: '/$guildId'
      fullPath: '/dashboard/$guildId'
      preLoaderRoute: typeof DashboardGuildIdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/guilds/': {
      id: '/api/guilds/'
      path: '/guilds'
      fullPath: '/api/guilds/'
      preLoaderRoute: typeof ApiGuildsIndexRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/dashboard/$guildId/': {
      id: '/dashboard/$guildId/'
      path: '/'
      fullPath: '/dashboard/$guildId/'
      preLoaderRoute: typeof DashboardGuildIdIndexRouteImport
      parentRoute: typeof DashboardGuildIdRouteRoute
    }
    '/dashboard/$guildId/activity': {
      id: '/dashboard/$guildId/activity'
      path: '/activity'
      fullPath: '/dashboard/$guildId/activity'
      preLoaderRoute: typeof DashboardGuildIdActivityRouteImport
      parentRoute: typeof DashboardGuildIdRouteRoute
    }
    '/dashboard/$guildId/ai': {
      id: '/dashboard/$guildId/ai'
      path: '/ai'
      fullPath: '/dashboard/$guildId/ai'
      preLoaderRoute: typeof DashboardGuildIdAiRouteImport
      parentRoute: typeof DashboardGuildIdRouteRoute
    }
    '/dashboard/$guildId/commands': {
      id: '/dashboard/$guildId/commands'
      path: '/commands'
      fullPath: '/dashboard/$guildId/commands'
      preLoaderRoute: typeof DashboardGuildIdCommandsRouteImport
      parentRoute: typeof DashboardGuildIdRouteRoute
    }
    '/dashboard/$guildId/reminders': {
      id: '/dashboard/$guildId/reminders'
      path: '/reminders'
      fullPath: '/dashboard/$guildId/reminders'
      preLoaderRoute: typeof DashboardGuildIdRemindersRouteImport
      parentRoute: typeof DashboardGuildIdRouteRoute
    }
    '/dashboard/$guildId/responders': {
      id: '/dashboard/$guildId/responders'
      path: '/responders'
      fullPath: '/dashboard/$guildId/responders'
      preLoaderRoute: typeof DashboardGuildIdRespondersRouteImport
      parentRoute: typeof DashboardGuildIdRouteRoute
    }
    '/dashboard/$guildId/schedules': {
      id: '/dashboard/$guildId/schedules'
      path: '/schedules'
      fullPath: '/dashboard/$guildId/schedules'
      preLoaderRoute: typeof DashboardGuildIdSchedulesRouteImport
      parentRoute: typeof DashboardGuildIdRouteRoute
    }
    '/dashboard/$guildId/send': {
      id: '/dashboard/$guildId/send'
      path: '/send'
      fullPath: '/dashboard/$guildId/send'
      preLoaderRoute: typeof DashboardGuildIdSendRouteImport
      parentRoute: typeof DashboardGuildIdRouteRoute
    }
    '/dashboard/$guildId/welcome': {
      id: '/dashboard/$guildId/welcome'
      path: '/welcome'
      fullPath: '/dashboard/$guildId/welcome'
      preLoaderRoute: typeof DashboardGuildIdWelcomeRouteImport
      parentRoute: typeof DashboardGuildIdRouteRoute
    }
    '/api/guilds/$guildId/': {
      id: '/api/guilds/$guildId/'
      path: '/guilds/$guildId'
      fullPath: '/api/guilds/$guildId/'
      preLoaderRoute: typeof ApiGuildsGuildIdIndexRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/guilds/$guildId/activity': {
      id: '/api/guilds/$guildId/activity'
      path: '/guilds/$guildId/activity'
      fullPath: '/api/guilds/$guildId/activity'
      preLoaderRoute: typeof ApiGuildsGuildIdActivityRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/guilds/$guildId/channels': {
      id: '/api/guilds/$guildId/channels'
      path: '/guilds/$guildId/channels'
      fullPath: '/api/guilds/$guildId/channels'
      preLoaderRoute: typeof ApiGuildsGuildIdChannelsRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/guilds/$guildId/members': {
      id: '/api/guilds/$guildId/members'
      path: '/guilds/$guildId/members'
      fullPath: '/api/guilds/$guildId/members'
      preLoaderRoute: typeof ApiGuildsGuildIdMembersRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/guilds/$guildId/messages': {
      id: '/api/guilds/$guildId/messages'
      path: '/guilds/$guildId/messages'
      fullPath: '/api/guilds/$guildId/messages'
      preLoaderRoute: typeof ApiGuildsGuildIdMessagesRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/guilds/$guildId/roles': {
      id: '/api/guilds/$guildId/roles'
      path: '/guilds/$guildId/roles'
      fullPath: '/api/guilds/$guildId/roles'
      preLoaderRoute: typeof ApiGuildsGuildIdRolesRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/guilds/$guildId/welcome': {
      id: '/api/guilds/$guildId/welcome'
      path: '/guilds/$guildId/welcome'
      fullPath: '/api/guilds/$guildId/welcome'
      preLoaderRoute: typeof ApiGuildsGuildIdWelcomeRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/guilds/$guildId/ai/': {
      id: '/api/guilds/$guildId/ai/'
      path: '/guilds/$guildId/ai'
      fullPath: '/api/guilds/$guildId/ai/'
      preLoaderRoute: typeof ApiGuildsGuildIdAiIndexRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/guilds/$guildId/ai/test': {
      id: '/api/guilds/$guildId/ai/test'
      path: '/guilds/$guildId/ai/test'
      fullPath: '/api/guilds/$guildId/ai/test'
      preLoaderRoute: typeof ApiGuildsGuildIdAiTestRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/guilds/$guildId/commands/': {
      id: '/api/guilds/$guildId/commands/'
      path: '/guilds/$guildId/commands'
      fullPath: '/api/guilds/$guildId/commands/'
      preLoaderRoute: typeof ApiGuildsGuildIdCommandsIndexRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/guilds/$guildId/commands/$id': {
      id: '/api/guilds/$guildId/commands/$id'
      path: '/guilds/$guildId/commands/$id'
      fullPath: '/api/guilds/$guildId/commands/$id'
      preLoaderRoute: typeof ApiGuildsGuildIdCommandsIdRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/guilds/$guildId/reminders/': {
      id: '/api/guilds/$guildId/reminders/'
      path: '/guilds/$guildId/reminders'
      fullPath: '/api/guilds/$guildId/reminders/'
      preLoaderRoute: typeof ApiGuildsGuildIdRemindersIndexRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/guilds/$guildId/reminders/$id': {
      id: '/api/guilds/$guildId/reminders/$id'
      path: '/guilds/$guildId/reminders/$id'
      fullPath: '/api/guilds/$guildId/reminders/$id'
      preLoaderRoute: typeof ApiGuildsGuildIdRemindersIdRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/guilds/$guildId/reminders/settings': {
      id: '/api/guilds/$guildId/reminders/settings'
      path: '/guilds/$guildId/reminders/settings'
      fullPath: '/api/guilds/$guildId/reminders/settings'
      preLoaderRoute: typeof ApiGuildsGuildIdRemindersSettingsRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/guilds/$guildId/responders/': {
      id: '/api/guilds/$guildId/responders/'
      path: '/guilds/$guildId/responders'
      fullPath: '/api/guilds/$guildId/responders/'
      preLoaderRoute: typeof ApiGuildsGuildIdRespondersIndexRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/guilds/$guildId/responders/$id': {
      id: '/api/guilds/$guildId/responders/$id'
      path: '/guilds/$guildId/responders/$id'
      fullPath: '/api/guilds/$guildId/responders/$id'
      preLoaderRoute: typeof ApiGuildsGuildIdRespondersIdRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/guilds/$guildId/schedules/': {
      id: '/api/guilds/$guildId/schedules/'
      path: '/guilds/$guildId/schedules'
      fullPath: '/api/guilds/$guildId/schedules/'
      preLoaderRoute: typeof ApiGuildsGuildIdSchedulesIndexRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/guilds/$guildId/schedules/$id/': {
      id: '/api/guilds/$guildId/schedules/$id/'
      path: '/guilds/$guildId/schedules/$id'
      fullPath: '/api/guilds/$guildId/schedules/$id/'
      preLoaderRoute: typeof ApiGuildsGuildIdSchedulesIdIndexRouteImport
      parentRoute: typeof ApiRouteRoute
    }
    '/api/guilds/$guildId/schedules/$id/send': {
      id: '/api/guilds/$guildId/schedules/$id/send'
      path: '/guilds/$guildId/schedules/$id/send'
      fullPath: '/api/guilds/$guildId/schedules/$id/send'
      preLoaderRoute: typeof ApiGuildsGuildIdSchedulesIdSendRouteImport
      parentRoute: typeof ApiRouteRoute
    }
  }
}

interface ApiRouteRouteChildren {
  ApiStatsRoute: typeof ApiStatsRoute
  ApiStatusRoute: typeof ApiStatusRoute
  ApiGuildsIndexRoute: typeof ApiGuildsIndexRoute
  ApiGuildsGuildIdActivityRoute: typeof ApiGuildsGuildIdActivityRoute
  ApiGuildsGuildIdChannelsRoute: typeof ApiGuildsGuildIdChannelsRoute
  ApiGuildsGuildIdMembersRoute: typeof ApiGuildsGuildIdMembersRoute
  ApiGuildsGuildIdMessagesRoute: typeof ApiGuildsGuildIdMessagesRoute
  ApiGuildsGuildIdRolesRoute: typeof ApiGuildsGuildIdRolesRoute
  ApiGuildsGuildIdWelcomeRoute: typeof ApiGuildsGuildIdWelcomeRoute
  ApiGuildsGuildIdIndexRoute: typeof ApiGuildsGuildIdIndexRoute
  ApiGuildsGuildIdAiTestRoute: typeof ApiGuildsGuildIdAiTestRoute
  ApiGuildsGuildIdCommandsIdRoute: typeof ApiGuildsGuildIdCommandsIdRoute
  ApiGuildsGuildIdRemindersIdRoute: typeof ApiGuildsGuildIdRemindersIdRoute
  ApiGuildsGuildIdRemindersSettingsRoute: typeof ApiGuildsGuildIdRemindersSettingsRoute
  ApiGuildsGuildIdRespondersIdRoute: typeof ApiGuildsGuildIdRespondersIdRoute
  ApiGuildsGuildIdAiIndexRoute: typeof ApiGuildsGuildIdAiIndexRoute
  ApiGuildsGuildIdCommandsIndexRoute: typeof ApiGuildsGuildIdCommandsIndexRoute
  ApiGuildsGuildIdRemindersIndexRoute: typeof ApiGuildsGuildIdRemindersIndexRoute
  ApiGuildsGuildIdRespondersIndexRoute: typeof ApiGuildsGuildIdRespondersIndexRoute
  ApiGuildsGuildIdSchedulesIndexRoute: typeof ApiGuildsGuildIdSchedulesIndexRoute
  ApiGuildsGuildIdSchedulesIdSendRoute: typeof ApiGuildsGuildIdSchedulesIdSendRoute
  ApiGuildsGuildIdSchedulesIdIndexRoute: typeof ApiGuildsGuildIdSchedulesIdIndexRoute
}

const ApiRouteRouteChildren: ApiRouteRouteChildren = {
  ApiStatsRoute: ApiStatsRoute,
  ApiStatusRoute: ApiStatusRoute,
  ApiGuildsIndexRoute: ApiGuildsIndexRoute,
  ApiGuildsGuildIdActivityRoute: ApiGuildsGuildIdActivityRoute,
  ApiGuildsGuildIdChannelsRoute: ApiGuildsGuildIdChannelsRoute,
  ApiGuildsGuildIdMembersRoute: ApiGuildsGuildIdMembersRoute,
  ApiGuildsGuildIdMessagesRoute: ApiGuildsGuildIdMessagesRoute,
  ApiGuildsGuildIdRolesRoute: ApiGuildsGuildIdRolesRoute,
  ApiGuildsGuildIdWelcomeRoute: ApiGuildsGuildIdWelcomeRoute,
  ApiGuildsGuildIdIndexRoute: ApiGuildsGuildIdIndexRoute,
  ApiGuildsGuildIdAiTestRoute: ApiGuildsGuildIdAiTestRoute,
  ApiGuildsGuildIdCommandsIdRoute: ApiGuildsGuildIdCommandsIdRoute,
  ApiGuildsGuildIdRemindersIdRoute: ApiGuildsGuildIdRemindersIdRoute,
  ApiGuildsGuildIdRemindersSettingsRoute:
    ApiGuildsGuildIdRemindersSettingsRoute,
  ApiGuildsGuildIdRespondersIdRoute: ApiGuildsGuildIdRespondersIdRoute,
  ApiGuildsGuildIdAiIndexRoute: ApiGuildsGuildIdAiIndexRoute,
  ApiGuildsGuildIdCommandsIndexRoute: ApiGuildsGuildIdCommandsIndexRoute,
  ApiGuildsGuildIdRemindersIndexRoute: ApiGuildsGuildIdRemindersIndexRoute,
  ApiGuildsGuildIdRespondersIndexRoute: ApiGuildsGuildIdRespondersIndexRoute,
  ApiGuildsGuildIdSchedulesIndexRoute: ApiGuildsGuildIdSchedulesIndexRoute,
  ApiGuildsGuildIdSchedulesIdSendRoute: ApiGuildsGuildIdSchedulesIdSendRoute,
  ApiGuildsGuildIdSchedulesIdIndexRoute: ApiGuildsGuildIdSchedulesIdIndexRoute,
}

const ApiRouteRouteWithChildren = ApiRouteRoute._addFileChildren(
  ApiRouteRouteChildren,
)

interface DashboardGuildIdRouteRouteChildren {
  DashboardGuildIdActivityRoute: typeof DashboardGuildIdActivityRoute
  DashboardGuildIdAiRoute: typeof DashboardGuildIdAiRoute
  DashboardGuildIdCommandsRoute: typeof DashboardGuildIdCommandsRoute
  DashboardGuildIdRemindersRoute: typeof DashboardGuildIdRemindersRoute
  DashboardGuildIdRespondersRoute: typeof DashboardGuildIdRespondersRoute
  DashboardGuildIdSchedulesRoute: typeof DashboardGuildIdSchedulesRoute
  DashboardGuildIdSendRoute: typeof DashboardGuildIdSendRoute
  DashboardGuildIdWelcomeRoute: typeof DashboardGuildIdWelcomeRoute
  DashboardGuildIdIndexRoute: typeof DashboardGuildIdIndexRoute
}

const DashboardGuildIdRouteRouteChildren: DashboardGuildIdRouteRouteChildren = {
  DashboardGuildIdActivityRoute: DashboardGuildIdActivityRoute,
  DashboardGuildIdAiRoute: DashboardGuildIdAiRoute,
  DashboardGuildIdCommandsRoute: DashboardGuildIdCommandsRoute,
  DashboardGuildIdRemindersRoute: DashboardGuildIdRemindersRoute,
  DashboardGuildIdRespondersRoute: DashboardGuildIdRespondersRoute,
  DashboardGuildIdSchedulesRoute: DashboardGuildIdSchedulesRoute,
  DashboardGuildIdSendRoute: DashboardGuildIdSendRoute,
  DashboardGuildIdWelcomeRoute: DashboardGuildIdWelcomeRoute,
  DashboardGuildIdIndexRoute: DashboardGuildIdIndexRoute,
}

const DashboardGuildIdRouteRouteWithChildren =
  DashboardGuildIdRouteRoute._addFileChildren(
    DashboardGuildIdRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardGuildIdRouteRoute: typeof DashboardGuildIdRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardGuildIdRouteRoute: DashboardGuildIdRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRouteRoute: ApiRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
